# Generated by Django 6.0.7 on 2026-07-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ifta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fiqh', models.CharField(choices=[('hanafi', 'Hanafi'), ('maliki', 'Maliki'), ('shafi', "Shafi'"), ('hanbali', 'Hanbali')], default='hanafi', max_length=20)),
            ],
        ),
    ]
