# Generated by Django 6.0.7 on 2026-07-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifta',
            name='fiqh',
            field=models.CharField(choices=[('hanafi', 'Hanafi'), ('maliki', 'Maliki'), ('shafi', "Shafi'"), ('hanbali', 'Hanbali')], max_length=20),
        ),
    ]
