# Generated by Django 6.0.7 on 2026-07-15 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_ifta_fiqh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifta',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
